export interface FlashcardData {
  id: string;
  category: "Law" | "Principles" | "Brokerage" | "Finance";
  question: string;
  answer: string;
}

export const flashcards: FlashcardData[] = [
  {
    id: "fl-re-001",
    category: "Principles",
    question: "What is the educational requirement for a Florida sales associate before their first license renewal?",
    answer: "Completion of a 45-hour post-licensing course.",
  },
  {
    id: "fl-re-002",
    category: "Law",
    question: "If a Florida sales associate fails to complete the required 45-hour post-licensing course before their first renewal, what is the status of their license?",
    answer: "Null and void.",
  },
  {
    id: "fl-re-003",
    category: "Finance",
    question: "In the context of real estate investment, what is defined as 'negative leverage'?",
    answer: "The condition where the cost of borrowed funds is higher than the rate of return on the investment.",
  },
  {
    id: "fl-re-004",
    category: "Finance",
    question: "On a Closing Disclosure, how is a binder deposit typically recorded?",
    answer: "As a credit to the buyer.",
  },
  {
    id: "fl-re-005",
    category: "Finance",
    question: "On a Closing Disclosure, how are unpaid property taxes and rental income typically recorded?",
    answer: "As a debit to the seller and a credit to the buyer.",
  },
  {
    id: "fl-re-006",
    category: "Finance",
    question: "In a 30-year fixed-rate fully amortized mortgage, how does the portion of the payment applied to principal change over time?",
    answer: "The amount applied to principal increases with each subsequent payment.",
  },
  {
    id: "fl-re-007",
    category: "Finance",
    question: "Which mortgage clause allows a lender to demand the full outstanding balance if the property is sold without the lender's consent?",
    answer: "Due-on-sale clause.",
  },
  {
    id: "fl-re-008",
    category: "Finance",
    question: "Which mortgage clause is activated when the borrower defaults, allowing the lender to demand the entire loan balance immediately?",
    answer: "Acceleration clause.",
  },
  {
    id: "fl-re-009",
    category: "Finance",
    question: "What is the function of the defeasance clause in a mortgage?",
    answer: "It ensures the lender releases the lien once the debt is fully paid.",
  },
  {
    id: "fl-re-010",
    category: "Law",
    question: "In terms of lien priority, which type of lien generally takes precedence over all others regardless of the filing date?",
    answer: "Real estate (property) tax liens and special assessment liens.",
  },
  {
    id: "fl-re-011",
    category: "Principles",
    question: "How many square feet are contained in one acre of land?",
    answer: "43,560 square feet.",
  },
  {
    id: "fl-re-012",
    category: "Principles",
    question: "How many acres are contained in one standard section of a township?",
    answer: "640 acres.",
  },
  {
    id: "fl-re-013",
    category: "Principles",
    question: "If an appraiser is using the Sales Comparison Approach and a comparable property has an extra bathroom worth $5,000 that the subject property lacks, what adjustment is made?",
    answer: "Subtract $5,000 from the comparable property's sales price.",
  },
  {
    id: "fl-re-014",
    category: "Law",
    question: "What is the name of the deed covenant where the grantor warrants they own the property and have the legal right to convey it?",
    answer: "Covenant of seisin.",
  },
  {
    id: "fl-re-015",
    category: "Law",
    question: "Florida practices which theory of mortgage lending, where the borrower retains title during the loan period?",
    answer: "Lien theory.",
  },
  {
    id: "fl-re-016",
    category: "Brokerage",
    question: "What is the presumed brokerage relationship in Florida if no other relationship is established in writing?",
    answer: "Transaction broker.",
  },
  {
    id: "fl-re-017",
    category: "Brokerage",
    question: "Which type of agency relationship in Florida includes a fiduciary duty to the principal?",
    answer: "Single agent relationship.",
  },
  {
    id: "fl-re-018",
    category: "Principles",
    question: "What are the legal rights associated with land abutting a flowing waterway, such as a river or stream?",
    answer: "Riparian rights.",
  },
  {
    id: "fl-re-019",
    category: "Principles",
    question: "What are the legal rights associated with land abutting non-flowing water, such as an ocean or lake?",
    answer: "Littoral rights.",
  },
  {
    id: "fl-re-020",
    category: "Finance",
    question: "How much does each discount point purchased by a borrower increase the lender's effective yield?",
    answer: "By 1/8 of 1% (or 0.125%).",
  },
  {
    id: "fl-re-021",
    category: "Principles",
    question: "Which legal description method utilizes a 'point of beginning' (POB) and compass directions?",
    answer: "Metes and bounds method.",
  },
  {
    id: "fl-re-022",
    category: "Principles",
    question: "What is the title of the imaginary line running north and south through Tallahassee used in the Government Survey Method?",
    answer: "Principal meridian.",
  },
  {
    id: "fl-re-023",
    category: "Law",
    question: "Can a Florida real estate sales associate perform an appraisal for a fee?",
    answer: "Yes, provided it is not for a federally related transaction and they follow USPAP guidelines.",
  },
  {
    id: "fl-re-024",
    category: "Law",
    question: "Under the Lead-Based Paint Hazard Reduction Act, what is the 'target year' for dwellings requiring specific lead disclosures?",
    answer: "Before 1978.",
  },
  {
    id: "fl-re-025",
    category: "Finance",
    question: "Which entity is the largest participant in the secondary mortgage market?",
    answer: "Fannie Mae.",
  },
  {
    id: "fl-re-026",
    category: "Finance",
    question: "Under Florida Constitutional Homestead law, what is the maximum standard tax exemption for a property valued over $75,000?",
    answer: "$50,000.",
  },
  {
    id: "fl-re-027",
    category: "Principles",
    question: "According to the Florida Residential Landlord and Tenant Act, how many days does a landlord have to return a security deposit if no claim is being made?",
    answer: "15 days.",
  },
  {
    id: "fl-re-028",
    category: "Principles",
    question: "If a landlord intends to make a claim on a tenant's security deposit, how many days do they have to notify the tenant?",
    answer: "30 days.",
  },
  {
    id: "fl-re-029",
    category: "Brokerage",
    question: "What is the illegal practice of a licensee channeling home seekers toward or away from certain neighborhoods based on protected class status?",
    answer: "Steering.",
  },
  {
    id: "fl-re-030",
    category: "Brokerage",
    question: "What is the illegal practice where a licensee induces a homeowner to sell by claiming that members of a protected class are moving into the neighborhood?",
    answer: "Blockbusting.",
  },
  {
    id: "fl-re-031",
    category: "Finance",
    question: "What is the illegal practice of a lender or insurance company denying coverage based on a property's geographic location in a specific neighborhood?",
    answer: "Redlining.",
  },
  {
    id: "fl-re-032",
    category: "Law",
    question: "Which Florida Statute governs the Department of Business and Professional Regulation (DBPR) and its licensing procedures?",
    answer: "F.S. 455.",
  },
  {
    id: "fl-re-033",
    category: "Law",
    question: "Which Florida Statute specifically regulates the practice of real estate?",
    answer: "F.S. 475.",
  },
  {
    id: "fl-re-034",
    category: "Principles",
    question: "In a joint tenancy with right of survivorship, if one co-owner dies, who receives their interest in the property?",
    answer: "The surviving co-owners, by operation of law.",
  },
  {
    id: "fl-re-035",
    category: "Brokerage",
    question: "What is the term for a real estate advertisement that fails to disclose the name of the brokerage firm?",
    answer: "Blind advertisement.",
  },
  {
    id: "fl-re-036",
    category: "Brokerage",
    question: "If a broker receives an escrow check on Tuesday, by which day must it be deposited into the escrow account?",
    answer: "By the end of business on Friday (within three business days).",
  },
  {
    id: "fl-re-037",
    category: "Law",
    question: "What is the term for a disciplinary penalty for a first-time minor violation that does not include a fine?",
    answer: "Notice of non-compliance.",
  },
  {
    id: "fl-re-038",
    category: "Principles",
    question: "Which form of co-ownership allows shares to be unequal and provides no right of survivorship?",
    answer: "Tenancy in common.",
  },
  {
    id: "fl-re-039",
    category: "Principles",
    question: "What is the term for a title search that provides a complete successive record of a property's ownership history?",
    answer: "Abstract of title.",
  },
  {
    id: "fl-re-040",
    category: "Law",
    question: "According to the Statute of Frauds, which real estate contracts must be in writing to be enforceable?",
    answer: "Purchase and sale contracts, deeds, mortgages, and leases longer than one year.",
  },
  {
    id: "fl-re-041",
    category: "Principles",
    question: "Which non-freehold estate is characterized by a specific, defined start and end date?",
    answer: "Estate for years.",
  },
  {
    id: "fl-re-042",
    category: "Law",
    question: "If a sales associate leaves a brokerage and takes original listing contracts, what crime may they be charged with?",
    answer: "Larceny.",
  },
  {
    id: "fl-re-043",
    category: "Law",
    question: "If a sales associate leaves a brokerage and takes copies of listing contracts, what violation may they be charged with?",
    answer: "Breach of trust.",
  },
  {
    id: "fl-re-044",
    category: "Finance",
    question: "In an adjustable-rate mortgage (ARM), what is the component that is a fixed percentage added to the index to determine the interest rate?",
    answer: "The margin.",
  },
  {
    id: "fl-re-045",
    category: "Principles",
    question: "What form of notice is achieved by recording a document in the public records?",
    answer: "Constructive notice (or legal notice).",
  },
  {
    id: "fl-re-046",
    category: "Principles",
    question: "What is the name of the set of guidelines that appraisers must follow when completing an appraisal?",
    answer: "USPAP (Uniform Standards of Professional Appraisal Practice).",
  },
  {
    id: "fl-re-047",
    category: "Principles",
    question: "A residential market with a high supply of available properties and low demand is known as a _____.",
    answer: "Buyer's market.",
  },
  {
    id: "fl-re-048",
    category: "Finance",
    question: "What is the formula for calculating a property owner's assessment for street paving?",
    answer: "(Front footage x Cost per foot x Owner's percentage of cost) ÷ 2.",
  },
  {
    id: "fl-re-049",
    category: "Finance",
    question: "What is the formula for calculating a property's taxable value for property taxes?",
    answer: "Assessed Value - Homestead Exemptions = Taxable Value.",
  },
  {
    id: "fl-re-050",
    category: "Principles",
    question: "How many sections are contained within a single township?",
    answer: "36 sections.",
  },
  {
    id: "fl-re-051",
    category: "Law",
    question: "Under the Florida Real Estate Commission rules, what is the maximum referral fee a licensee can pay to an unlicensed person who is a tenant in an apartment complex?",
    answer: "$50.",
  },
  {
    id: "fl-re-052",
    category: "Law",
    question: "A deed is valid even if it is not _____.",
    answer: "Recorded.",
  },
  {
    id: "fl-re-053",
    category: "Law",
    question: "In a real estate transaction, when is legal title actually conveyed from the grantor to the grantee?",
    answer: "Upon voluntary delivery and acceptance of the deed.",
  },
  {
    id: "fl-re-054",
    category: "Law",
    question: "Which clause in a deed is known as the 'to have and to hold' clause and defines the bundle of rights being conveyed?",
    answer: "Habendum clause.",
  },
  {
    id: "fl-re-055",
    category: "Law",
    question: "What is the name of the Florida statute that requires a developer to provide a disclosure summary to buyers in a Homeowners Association?",
    answer: "F.S. 720.",
  },
  {
    id: "fl-re-056",
    category: "Law",
    question: "If a broker's license is revoked, what happens to the licenses of the sales associates registered under that broker?",
    answer: "They are placed on involuntary inactive status.",
  },
  {
    id: "fl-re-057",
    category: "Law",
    question: "What type of deed is most commonly used to clear a 'cloud on title' or resolve an easement issue?",
    answer: "Quitclaim deed.",
  },
  {
    id: "fl-re-058",
    category: "Principles",
    question: "What term describes the most profitable and legally permissible single use of a property?",
    answer: "Highest and best use.",
  },
  {
    id: "fl-re-059",
    category: "Finance",
    question: "What type of mortgage covers more than one parcel of land and usually contains a 'partial release clause'?",
    answer: "Blanket mortgage.",
  },
  {
    id: "fl-re-060",
    category: "Finance",
    question: "What type of mortgage includes both real property and personal property (like appliances) as security for the debt?",
    answer: "Package mortgage.",
  },
  {
    id: "fl-re-061",
    category: "Law",
    question: "If a licensee is paid a settlement from the Real Estate Recovery Fund for a claim not involving an Escrow Disbursement Order, what is the mandatory penalty?",
    answer: "Automatic suspension of the license until the fund is repaid in full plus interest.",
  },
  {
    id: "fl-re-062",
    category: "Law",
    question: "A sales associate must notify the DBPR of a change of employer within how many days?",
    answer: "10 days.",
  },
  {
    id: "fl-re-063",
    category: "Finance",
    question: "What is the name of the economic indicator used to adjust the interest rate on an ARM?",
    answer: "The Index.",
  },
  {
    id: "fl-re-064",
    category: "Finance",
    question: "What is the tax rate for the intangible tax on a new mortgage in Florida?",
    answer: "0.002 (or 2 mills) per dollar of new debt.",
  },
  {
    id: "fl-re-065",
    category: "Finance",
    question: "What is the state-mandated fee for documentary stamps on a deed in Florida (excluding Miami-Dade)?",
    answer: "$0.70 per $100 of the sales price.",
  },
  {
    id: "fl-re-066",
    category: "Finance",
    question: "What is the state-mandated fee for documentary stamps on a promissory note in Florida?",
    answer: "$0.35 per $100 of the mortgage amount.",
  },
  {
    id: "fl-re-067",
    category: "Brokerage",
    question: "A property manager who deposits $7,000 of personal funds into an escrow account containing $1,000 of tenant funds is guilty of _____.",
    answer: "Commingling.",
  },
  {
    id: "fl-re-068",
    category: "Brokerage",
    question: "What is the term for the illegal use of escrow funds for a broker's personal or business use?",
    answer: "Conversion.",
  },
  {
    id: "fl-re-069",
    category: "Brokerage",
    question: "When a broker has a good-faith doubt regarding which party is entitled to escrow funds, they must notify the FREC within _____.",
    answer: "15 business days.",
  },
  {
    id: "fl-re-070",
    category: "Law",
    question: "What is the term for an agreement to substitute a new party or a new obligation for an existing one in a contract?",
    answer: "Novation.",
  },
  {
    id: "fl-re-071",
    category: "Principles",
    question: "Which appraisal approach is most suitable for a one-of-a-kind property, such as a courthouse or a church?",
    answer: "Cost approach.",
  },
  {
    id: "fl-re-072",
    category: "Principles",
    question: "Which appraisal approach is most suitable for a vacant lot or a single-family residence?",
    answer: "Sales comparison approach.",
  },
  {
    id: "fl-re-073",
    category: "Principles",
    question: "What is the term for a loss in property value due to factors outside the property boundaries, such as an adjacent airport?",
    answer: "External (or economic) obsolescence.",
  },
  {
    id: "fl-re-074",
    category: "Principles",
    question: "What is the term for a loss in property value due to an outdated design or poor floor plan?",
    answer: "Functional obsolescence.",
  },
  {
    id: "fl-re-075",
    category: "Finance",
    question: "What is the formula for calculating the Gross Rent Multiplier (GRM)?",
    answer: "Sales Price ÷ Gross Annual Rent.",
  },
  {
    id: "fl-re-076",
    category: "Finance",
    question: "What is the formula for calculating the capitalization rate (Cap Rate)?",
    answer: "Net Operating Income (NOI) ÷ Value (or Sales Price).",
  },
  {
    id: "fl-re-077",
    category: "Law",
    question: "What is the name of the law that requires lenders to provide a good-faith estimate of closing costs and prohibits illegal kickbacks?",
    answer: "RESPA (Real Estate Settlement Procedures Act).",
  },
  {
    id: "fl-re-078",
    category: "Law",
    question: "If a person dies 'intestate' and has no heirs, what happens to their real property?",
    answer: "It 'escheats' to the state.",
  },
  {
    id: "fl-re-079",
    category: "Law",
    question: "Which type of deed provides the greatest protection to the buyer?",
    answer: "General Warranty Deed.",
  },
  {
    id: "fl-re-080",
    category: "Finance",
    question: "What are the two components of the interest rate on an Adjustable Rate Mortgage (ARM)?",
    answer: "Index and Margin.",
  },
  {
    id: "fl-re-081",
    category: "Law",
    question: "What is the purpose of the 'Property Tax Disclosure' given to buyers?",
    answer: "To warn them that the seller's current tax amount may not be the same amount the buyer will pay.",
  },
  {
    id: "fl-re-082",
    category: "Principles",
    question: "In a Metes and Bounds description, what direction is the opposite of N 45° E?",
    answer: "S 45° W.",
  },
  {
    id: "fl-re-083",
    category: "Principles",
    question: "What is the term for a non-freehold estate where a tenant stays in possession of the property after their lease expires without the landlord's consent?",
    answer: "Tenancy at sufferance.",
  },
  {
    id: "fl-re-084",
    category: "Principles",
    question: "Which type of co-ownership is specifically for married couples in Florida?",
    answer: "Tenancy by the entireties.",
  },
  {
    id: "fl-re-085",
    category: "Law",
    question: "What is the name of the law that requires certain real estate contracts to be in writing to be enforceable?",
    answer: "Statute of Frauds.",
  },
];